# Generated by Django 5.2 on 2025-05-22 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='control.atributo')),
            ],
            options={
                'verbose_name': 'Opción de Atributo',
                'verbose_name_plural': 'Opciones de Atributo',
                'ordering': ['atributo', 'orden', 'valor'],
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(default='N/A', max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.atributo')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.opcionatributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.producto')),
            ],
            options={
                'ordering': ['atributo__nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.ManyToManyField(through='control.ProductoAtributo', to='control.atributo'),
        ),
    ]
