# Generated by Django 5.2 on 2025-05-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_atributo_opcionatributo_productoatributo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoatributo',
            options={},
        ),
    ]
