# Generated by Django 5.2 on 2025-05-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_productoatributo_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoatributo',
            unique_together=set(),  # Elimina cualquier unique_together existente
        ),
    ]
