# Generated by Django 5.2 on 2025-05-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_productoatributo_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoatributo',
            options={'ordering': ['atributo__nombre']},
        ),
        migrations.RemoveField(
            model_name='productoatributo',
            name='valor',
        ),
    ]
