# Generated by Django 5.2 on 2025-05-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_productoatributo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoatributo',
            options={},
        ),
        migrations.AlterField(
            model_name='productoatributo',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.opcionatributo'),
        ),
        migrations.AlterUniqueTogether(
            name='productoatributo',
            unique_together={('producto', 'atributo', 'opcion')},
        ),
    ]
