# Generated by Django 5.2 on 2025-05-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_productoatributo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoatributo',
            options={'ordering': ['atributo__nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='productoatributo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productoatributo',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.opcionatributo'),
        ),
    ]
