# Generated by Django 5.2 on 2025-05-26 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_alter_productoatributo_atributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoatributo',
            name='opcion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='control.opcionatributo',default='valor_por_defecto'),
        ),
    ]
