# Generated by Django 5.2 on 2025-05-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_alter_productoatributo_opcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoatributo',
            name='opcion',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='control.opcionatributo'),
        ),
    ]
