# Generated by Django 5.2 on 2025-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_productoatributo_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionatributo',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
