# Generated by Django 5.2 on 2025-05-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_opcionatributo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionatributo',
            name='color',
        ),
    ]
