# Generated by Django 5.2 on 2025-05-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_remove_opcionatributo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionatributo',
            name='color',
            field=models.CharField(default='#4e73df', max_length=7),
        ),
    ]
