# Generated by Django 5.2 on 2025-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_opcionatributo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionatributo',
            name='color',
            field=models.CharField(default='#4e73df', help_text='Color HEX (ej: #ff0000)', max_length=7),
        ),
    ]
